enum LobbyDestroyedReason {
    INACTIVITY_TIMEOUT = 'INACTIVITY_TIMEOUT',
    INVITE_TIMEOUT = 'INVITE_TIMEOUT',
    MANUAL = 'MANUAL',
    USER_LEFT = 'USER_LEFT',
    USER_TRADING_INELIGIBLE = 'USER_TRADING_INELIGIBLE',
    SPOOFED_ITEM = 'SPOOFED_ITEM',
    TRADE_ERRORED = 'TRADE_ERRORED'
}

export default LobbyDestroyedReason;
