enum TradeBotState {
    NOT_READY = 'NOT_READY',
    AUTHENTICATED = 'AUTHENTICATED',
    AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED',
    CONNECTED = 'CONNECTED',
    READY = 'READY'
}

export default TradeBotState;
